### ISSUE TITLE
Connectet with a Database

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#12]

**Comment by FranziGraml** [comment]
# Value Proposition

As a
I need to store my data on a database
to be able to save my updates and grant access online

# Description

Connectet with a Database

# Acceptance Criteria

- [ ] After adding new posts and updating the website, my new posts will remain


# Tasks



- [ ] Add a new branch "connect-database"
- [ ] Create a new connection to MongoDB
- [ ] Create a src/lib/database.js
- [ ] Import mongoose
- [ ] Import Data into Database without ID's
- [ ] Create src/lib/swr-fetcher.js
- [ ] Import SWR Hook on index.js
- [ ] Create a getStaticProps function with fallback
- [ ] Add SWRConfig
- [ ] Create src/lib/models/Post.js
- [ ] Create pages/api/posts.js
- [ ] Create pages/api/post/[id].js
- [ ] 
# Complexity

XL


Complexity

XL

**Comment by irenepapaspyratos** [comment]
Hey Franzi,
as a reader I would like to know, which role needs this feature and I would change the 'Connectet' to 'Connect' in the description. 
And I think - if you don't want to have the posts on your homepage - you need a pages/posts, too.

**Comment by FranziGraml** [comment]
Hi Irene.
Thanks for you reviewing.
I will implement your comment.
The page 'posts' I have since yesterday.
