### ISSUE TITLE
Header Nav Bar with routing

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#14]

**Comment by FranziGraml** [comment]
# Value Proposition

As a user
I need to navigate
to be able to the possibility of switching pages with different functions/features


# Description

The footer NavBar allows the user to navigate between the different pages


# Acceptance Criteria

- [ ] A Header is displayed on the each page (HomePage 1, post-board 2)
- [ ] Every item of the NavBar should be seperated visually
- [ ] each item should be clickable
- [ ] the user should be redirct to the corresponding page Onclick
    
# Task

- [ ] Create a Navigation Component
- [ ] Create in pages a new file HomePage
- [ ] Create in pages a new file postBoard
- [ ] Implement routing via next/link
- [ ] each item should link to its corresponding page
- [ ] Add basic styling


#Complexity
M
