### ISSUE TITLE
Styling postPage with PostCard

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#20]

**Comment by FranziGraml** [comment]
# Value Proposition

As a user
I need the page must be attractive and clear.
to be able to have a better overview 

# Description

Styling for the "posts" page and postscards.

# Acceptance Criteria

- [ ] the page is responsive
- [ ] the cards are recognizable as cards
- [ ] the writing is easy to read
- [ ] the buttons/ icons are well visible
- [ ] the colors are not too intrusive

# Tasks

(for developers team)

- [ ] Create a new branch " styling post-board"
- [ ] Add styling for the postcard with headlines and Icons
- [ ] Add styling for the "posts" page with headline and Icons

# Complexity
M

**Comment by cintiavazquez** [comment]
Good US, Franzi! :)
