### ISSUE TITLE
Styling Header with Navbar

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#21]

**Comment by FranziGraml** [comment]
# Value Proposition
As a user
I need the "header/navbar" should be well structured and clear
to be able to a better overview.


# Description

Styling Header with Navbar

# Acceptance Criteria

- [ ] the header is responsive
- [ ] the navbar is easy to read
- [ ] the icons are well visible

# Tasks

(for developers team)

- [ ] Create a new branch "styling header and navbar"
- [ ] Add styling for the header with perfect colors
- [ ] Add styling for the navbar with icons

# Complexity
s
