### ISSUE TITLE
List posts

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#3]

**Comment by FranziGraml** [comment]
# Value Proposition

As a user
I need to see a list of reviews from all users
I need to be able to get an overview of all  written messages

# Description

![User Storie #2](https://user-images.githubusercontent.com/94370292/167148822-fd886bc5-1ee5-4b09-ad14-693217ed0b61.png)



# Acceptance Criteria

- [ ] Each posts should be visually separated
- [ ] Display important details for each posts
- [ ] All created posts shold be displyed


# Tasks



- [ ]  Create a branch "display-all-posts"
- [ ] Create the data structure that hold an array of multiple products
- [ ] Create a new component to map over array
- [ ] The component receives product details via props
- [ ] Add component to the app
- [ ] Apply basic styling to visually isolate each create posts from all others
- [ ] Add test to check if all given products are rendered



# Complexity
M

**Comment by aclaes** [comment]
Hi  Franzi,

good user story! I have some small comments.

I think the value proposition could be a bit more specific regarding the generated values for the user. It could be something like “to be able to get on overview of all offerings for co-working and co-living locations”


Regarding the acceptance criteria you should get more into detail. It’s not quite clear which data should be displayed per post (username, message, contact, etc.). Please also consider labels/headlines if there are any. If there is another story describing the details of each card, please link to it like this `#1`.

Please don’t forget to write tests. Consider adding this to the “tasks” section.
