### ISSUE TITLE
Create a post

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#4]

**Comment by FranziGraml** [comment]
# Value Proposition

As a User
I need to create a new post
to be able to offer my help or to ask for help or somethink else

# Description
![User Storie #3](https://user-images.githubusercontent.com/94370292/167297097-4c80daae-352d-4734-8090-341e976ed528.png)



# Acceptance Criteria

- [ ] An input field for the Usernam is displayed, labeled "Username"
- [ ] An input field for the post-message is displayed, labeled "Post"
- [ ] The post-message must be text with 50-500 characters
- [ ] Two input field for contact is displayed, labeled "mail" and "mobile-phone"
- [ ] A button to creat a new post is displayed, labeled "create a new Post"
- [ ] After posting, the fields are cleared
- [ ] After posting the new posts-message will appear on the list of posts


# Tasks



- [ ] Create a new branch "create a post"
- [ ] Create a form component
- [ ] Create a input component
- [ ] Add form fiels with labels
- [ ] Create a submit button
- [ ] Form fields are controlled within a state
- [ ] Mark all form fields as required
- [ ] Add text length validation
- [ ] Store the data after submitting the form with valid data
- [ ] Write tests


# Complexity
XL

**Comment by aclaes** [comment]
Hi Franzi,

great user story! 

There is one thing you should change: If I understood your acceptance criteria correctly, you are planning to show the labels as placeholder for your input fields. Labels and placeholders have a different meaning. Please use an actual `<label>`  element for the label – that is still visible after the user entered text into the field. The placeholder might be used as an example for text to enter into the field (e.g. “[john@doe.com](mailto:john@doe.com)”  for the mail field)

In addition some typos:

- Value Proposition: “myself” instead of “himself”
- Acceptance Criteria 2: “A form appears” instead of “A form field appears“
- Acceptance Criteria 3: “Username” instead of “Usernam”

**Comment by FranziGraml** [comment]
Hi Alex,

You are absolutely right! I will do it with actaul `<label>` element and improve the typos.
Thanks for you review
