### ISSUE TITLE
Create a delete function

### ISSUE THREAD

**Issue by FranziGraml** [FranziGraml/capstone-project#9]

**Comment by FranziGraml** [comment]
# Value Proposition

As a ...user
I need ...to delete my written Post
to be able to ...to sort out old post-messages

# Description
![Image](https://user-images.githubusercontent.com/94370292/169254771-4b5f3b29-660f-40d7-a64d-a1e877497899.png)

(


# Acceptance Criteria


- [ ] A button to delete the product is displayed, labeled "delete"
- [ ]  When the delete button is pressed, a warning pop-up message appears ("Do you really want to delete this review?)
- [ ] 

!


 
# Tasks


-[ ] Add a new branch "create-delete-button"
- [ ] Add a delete button with an on-Click event to the review-card
- [ ] Create a Button with the label "delete"
- [ ] Add an onClick event to the button




# Complexity
M
